### ISSUE TITLE
Modify to work with Forklift

### ISSUE THREAD

**Issue by jacobdadams** [agrc/auditor#11]
- [x] Add forklift framework
~- [ ] Abridge report to pass to forklift logging~ Moved to issue #16 
- [x] Convert prints to logs

**Comment by jacobdadams** [comment]
[ ] figure out when to run.

**Comment by jacobdadams** [comment]
Decided to run outside of forklift as a scheduled task, closing.

**Comment by steveoh** [comment]
I would recommend cribbing a little of the forklift logic around error handling and reporting since it will be a scheduled task.

**Comment by jacobdadams** [comment]
I'm guessing you're referring to the custom `global_exception_handler`, `_setup_logging`, and `messages.py` stuff?
