### ISSUE TITLE
Find duplicate AGOL titles

### ISSUE THREAD

**Issue by jacobdadams** [agrc/auditor#27]
Search AGOL for items with duplicate titles (either search for each one in the metatable, or do a site-wide search).

**Comment by steveoh** [comment]
Do you looping over every item in our org at some point? Keeping a hash of the names be more performant than searching.

**Comment by jacobdadams** [comment]
I have not thought about implementation yet. I just got my ten seconds worth of brain bandwidth down on (internet) paper to revisit when I have the time to properly think about it :)
