### ISSUE TITLE
Check and fix cacheMaxAge

### ISSUE THREAD

**Issue by jacobdadams** [agrc/auditor#35]
set the max time before clients check for new data to 23 hours for forklifted items (ie, in metatables), as forklift updates at most once every day.

```py
manager = arcgis.features.FeatureLayerCollection.fromitem(item).manager
manager.update_definition({'cacheMaxAge': 82800}) #: 23 hours of seconds
```

**Comment by stdavis** [comment]
Could this cause some clients to not see updates for almost a day after we have pushed them? For example, their clock starts counting right before we push updates. I wonder if we should cut it back to something like six hours?

**Comment by jacobdadams** [comment]
That's a good point. I'm curious what our policy/procedure has been in the past regarding how soon updates show up in various places—I remember talking about it during the SGID10 > internal discussion but don't remember the specifics.
