### ISSUE TITLE
Create branded thumbnails for static and shelved datasets

### ISSUE THREAD

**Issue by steveoh** [agrc/auditor#41]
It would be nice, at a glance, to be able to tell the status of a dataset without having to look at the tags. Using our brand thumbnail with static or shelved text on it would be a nice enhancement.

e.g. https://utah.maps.arcgis.com/home/item.html?id=110d43fbfacc411b8e74f4d12b63d881

**Comment by jacobdadams** [comment]
I like this idea. Couple of questions:

-  My first idea is to make the shelved thumbnail mirror the others. Should we try creating a periodic-table-style shelved icon, or should we go for something different in that area, or do a completely different style of thumbnail altogether?
- Static items should be getting their standard category icon. Are we ok to keep that? They're still considered part of the main, curated set of items.

**Comment by steveoh** [comment]
![image](https://user-images.githubusercontent.com/325813/96907648-bc136f80-1458-11eb-8400-0489530d240b.png)

I wonder if we change the color of the border and/or replace the `Lo Location` with maybe a calendar and the text `shelved` below? I also think we should append some text to the description that says 

> This data is marked as `Shelved` since it has historical relevance but is not the most recent data

**Comment by jacobdadams** [comment]
This thumbnail seems to be the consensus favorite. 

![shelved](https://user-images.githubusercontent.com/38168030/99693922-1d733200-2a49-11eb-894d-cb494e123b8d.png)
