### ISSUE TITLE
Ctrl-C won't stop once in fixing loop

### ISSUE THREAD

**Issue by jacobdadams** [agrc/auditor#9]
You can't Ctrl-C to stop the fixes. Probably due to overly-aggressive try/finally statement.

**Comment by jacobdadams** [comment]
There looks like two separate issues at play here.

1. As soon as the code touches an arcpy.something call, the rest of the execution ignores ctrl-c. Verified by hard-coding a metadata dictionary entry and commenting out the arcpy.exists/arcpy.metadata calls in the checker. Currently investigating whether this is expected behavior or a bug.
1. The checker.check_x() methods seem to trap ctrl-c's at the method level. As it loops through all the items, ctrl-c cancels that particular item rather than hitting the try/except/finally structure outside of the loop. It just quickly moves onto the next item. This is annoying but ok as the checks don't make any changes we'd want to log for manual roll-back, so we can just kill the window to stop if we need to.

Assuming the arcpy headache can be solved, adding 
```py
except KeyboardInterrupt:
    print('Interrupted by Ctrl-c')
```
Allows you to bomb out of the fixes while still writing the log file for any that have already been completed. 

While trying to solve the arcpy headache, you can successfully interrupt the program and hit the `finally` clause to write the log file by causing a network interruption, which throws up a network-related exception that isn't handled.

**Comment by steveoh** [comment]
This seems like an issue that isn't really worth spending a lot of time on unless you are very interested to get to the bottom of it.

**Comment by jacobdadams** [comment]
My concern is that the only way to cancel a fix operation is to close the interpreter, which prevents the log file from being written so you lose any data about what has been done. However, you're probably right, the impact is probably too small to justify the time to fix it.
